### ISSUE TITLE
i dont own the vehicle

### ISSUE THREAD

**Issue by CptNoHand** [MaDHouSe79/qb-parking#14]
after restart. it says i dont own the vehicle..
any fixes for that?

**Comment by MaDHouSe79** [comment]
are you using a other vehiclekey script than qb-vehiclekeys?

**Comment by CptNoHand** [comment]
No idk why it is like that. So you think its on my end?--Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 05.02.22, 18:17 schrieb MaDHouSe79 ***@***.***>:

   
  are you using a other vehiclekey script than qb-vehiclekeys?

**Comment by MaDHouSe79** [comment]
I never said that the issue is on your end, i ask you if you are using a other script than qb-vehiclekeys, cause if you do, than it make sence that you are not the owner of this vehicle. but if you do use qb-vehiclekeys than you have to add code to your qb-vehiclekeys you can find this in the README.md how to do this.

**Comment by CptNoHand** [comment]
no, i didnt mean that you said that either, i just wanted to ask, if you think its me. 

i did that now. Do you know about the offset? some vehicles begin to float, after restarts

**Comment by MaDHouSe79** [comment]
Yeah i have to fix that, i do that soon, it has to do somthing with the times i think, but ill take a look at it thank for notice. 
👊😉👍

**Comment by CptNoHand** [comment]
works now, just the offsets get a bit odd, but it works. 

why you got rid of the option to enable that for everyone without adding vips?

**Comment by MaDHouSe79** [comment]
i do this because your players wil get issues is you have free for all parking, remember that all the cars are spawned in world and if you have 100 cars than you get a lot, a very lot lag spiks, and to avoid this for all players i have done this so people that are vip or are most online on your server, you can give then this option. it is not recommanded to use this for al your players on your server, cause this wil cause issues.
