### ISSUE TITLE
Some vehicles dissapears after parking

### ISSUE THREAD

**Issue by epereza** [MaDHouSe79/qb-parking#30]
They dissapear cause they don't have a modelname in the database. How can i solve it? They are all configured by the same way in qb-core/shared/vehicles.lua

![heidisql_UJHfW3NkdG](https://user-images.githubusercontent.com/50680351/171992132-b41a1534-891c-4e9c-ad54-a0a020347f2a.png)

**Comment by epereza** [comment]
With parking-lite it's not happening. Even modelname is NULL, vehicle is spawned

![FiveM_b2612_GTAProcess_DNyldyyDwW](https://user-images.githubusercontent.com/50680351/171994946-46be763d-ea4b-493d-9c47-0773c5b2d8d4.jpg)

![heidisql_nXbgaEAANn](https://user-images.githubusercontent.com/50680351/171994965-e20c07ef-7818-475a-93a4-b9931b4756ce.png)

**Comment by MaDHouSe79** [comment]
make sure your vehicle.meta is correct made ;)

**Comment by epereza** [comment]
I've taking a look at the supposed good .metas comparing them with bads, and everything looks correct. I don't know where the problem can come from. I´ll be using parkinglite at the moment since I can find the issue. Thank you anyway.

**Comment by MaDHouSe79** [comment]
the issue is that the vehicle is stored as NULL and not as model name, if your model names is not add correctly you also get this.

This callback is the issue: QBCore.Functions.SetVehicleProperties(VehicleEntity, vehicleData.vehicle.props)

Some vehicles dont have this in the vehiclemeta props so it stores as NULL and not as model name.

**Comment by epereza** [comment]
Done with an script, excuse me for bothering and thank you for yhour work

**Comment by MaDHouSe79** [comment]
You're welcome! 👊😁👍
